// The controls a lab card shows ON ITS FACE: the few inputs worth changing while
// you watch. A name alone is auto-typed from the engine's own ParamDef (options →
// dropdown, otherwise a text box); `[name, min, max, step]` makes a slider.
// Everything else stays in the Properties panel. Kept apart from the engines so
// a new engine runs without any entry here, and so tuning a control never means
// touching algorithm code.

export type QuickSpec = string | [name: string, min: number, max: number, step: number]

export const QUICK: Record<string, QuickSpec[]> = {
  sched: ['algo', ['quantum', 1, 10, 1], 'procs'],
  paging: ['algo', ['frames', 1, 8, 1], 'refs'],
  disk: ['algo', ['head', 0, 199, 1], 'sweep', 'queue'],
  banker: ['request', 'max', 'alloc'],
  memfit: ['algo'],
  cache: ['mapping', 'policy', ['lines', 1, 16, 1], ['ways', 1, 8, 1], 'addrs'],
  numconv: ['n', ['bits', 2, 16, 1]],
  ieee754: ['value', 'format'],
  booth: ['m', 'q', ['bits', 2, 8, 1]],
  pipeline: ['forwarding', 'prog'],
  kmap: ['vars'],
  cpu8085: ['program', 'memory'],
  crc: ['data', 'generator'],
  hamming: ['data', ['error', 0, 11, 1]],
  linecode: ['bits'],
  modulation: ['scheme', ['cycles', 1, 6, 1]],
  pcm: [['fm', 0.5, 4, 0.5], ['fs', 2, 16, 1], ['bits', 1, 6, 1]],
  fourier: ['shape', ['harmonics', 1, 25, 1]],
  arq: ['protocol', ['window', 1, 8, 1], ['frames', 4, 12, 1]],
  subnet: ['address', 'hosts'],
  routing: ['algo', 'source', 'graph'],
  tcp: ['variant', ['rounds', 8, 40, 1], ['ssthresh', 4, 32, 1]],
  sorting: ['algo', 'values'],
  hashing: ['method', ['size', 5, 17, 1], 'keys'],
  huffman: ['text'],
  bst: ['mode', 'ops'],
  heap: ['kind'],
  btree: ['variant', ['order', 3, 6, 1]],
  graphalgo: ['algo', 'start', 'graph'],
  infix: ['expr'],
  hanoi: [['disks', 1, 6, 1]],
  dfa: ['input', 'spec'], nfa: ['input', 'spec'], pda: ['input', 'spec'], tm: ['input', 'spec'],
  cfg: ['string', 'grammar'],
  rootfind: ['method', 'f', 'tol'],
  integrate: ['rule', 'f', ['n', 2, 32, 1]],
  ode: ['f', ['h', 0.01, 0.5, 0.01]],
  gauss: ['pivoting', 'matrix'],
  iterative: ['method', ['iterations', 1, 20, 1], 'matrix'],
  interp: [['at', 0, 3, 0.1]],
  heat1d: [['r', 0.05, 0.6, 0.05], ['steps', 5, 200, 5], ['nodes', 5, 21, 2]],
  gd: ['f', ['lr', 0.01, 1.2, 0.01], ['x0', -2, 6, 0.5], ['steps', 1, 40, 1]],
  regression: ['points'],
  dist: ['kind', ['p', 0.05, 0.95, 0.05], ['lambda', 1, 15, 1], ['sigma', 0.3, 3, 0.1]],
  bayes: [['prior', 0.001, 0.5, 0.001], ['sensitivity', 0.5, 1, 0.01], ['specificity', 0.5, 1, 0.01]],
  clt: ['population', ['n', 1, 100, 1]],
  confint: [['n', 5, 100, 5], ['intervals', 10, 100, 5], 'zcrit'],
  montecarlo: [['points', 50, 2000, 50]],
  mm1: [['lambda', 0.1, 1.5, 0.05], ['mu', 0.5, 2, 0.05]],
  lcg: ['a', 'c', 'm'],
  markov: [['steps', 1, 30, 1], 'matrix'],
  search: ['algo', 'grid'],
  minimax: ['pruning', ['branching', 2, 3, 1]],
  perceptron: [['lr', 0.1, 2, 0.1], ['epochs', 1, 30, 1], 'data'],
  kmeans: [['k', 1, 5, 1], 'points'],
  ga: [['generations', 1, 30, 1], ['mutation', 0, 0.3, 0.01], ['population', 4, 12, 1]],
  mlp: [['units', 2, 6, 1], ['lr', 0.1, 3, 0.1]],
  fuzzy: [['temp', 0, 45, 1]],
  raster: ['algo', ['grid', 8, 24, 1]],
  clip: ['algo'],
  transform2d: ['ops'],
  bezier: ['t'],
  project3d: [['rx', 0, 90, 1], ['ry', 0, 90, 1], ['distance', 2, 10, 0.5], 'mode'],
  phong: [['ka', 0, 1, 0.05], ['kd', 0, 1, 0.05], ['ks', 0, 1, 0.05], ['shininess', 1, 100, 1]],
  fd: ['closureOf', 'fds'],
  serializability: ['schedule'],
  relalg: ['op', 'r', 's'],
  blocks: [['time', 1, 20, 1], 'blocks'],
}

/** The input a lab's title is the handle for: click the title on the picture and
 *  type a new value there. Engines may also make finer things clickable (cells,
 *  bits, grid squares) with `act()`; this just guarantees every engine has one
 *  obvious place to start. */
export const PRIMARY: Record<string, string> = {
  sched: 'procs', paging: 'refs', disk: 'queue', banker: 'max', memfit: 'requests', cache: 'addrs',
  ieee754: 'value', booth: 'm', pipeline: 'prog', crc: 'data', hamming: 'data', linecode: 'bits',
  modulation: 'bits', pcm: 'fm', arq: 'lose', subnet: 'address', routing: 'graph', tcp: 'timeouts',
  rootfind: 'f', integrate: 'f', ode: 'f', gauss: 'matrix', iterative: 'matrix', interp: 'points',
  gd: 'f', regression: 'points', markov: 'matrix', search: 'grid', minimax: 'leaves',
  perceptron: 'data', kmeans: 'points', clip: 'line', transform2d: 'ops', bezier: 'points',
  fd: 'fds', serializability: 'schedule', relalg: 'r', blocks: 'blocks', fuzzy: 'temp',
  dist: 'n', bayes: 'prior', clt: 'n', confint: 'n', montecarlo: 'points', mm1: 'customers', lcg: 'seed',
  ga: 'generations', mlp: 'epochs', raster: 'polygon', project3d: 'rx', phong: 'shininess', fourier: 'harmonics',
  heat1d: 'steps',
}
