import { lesson } from '../kit.mjs'
export default ({ lab, dia, cpp, q, pr, step, sec, term, run }) => {
  const v = '5 1 4 2 8 9 3'
  const S = Object.fromEntries(['bubble', 'insertion', 'selection', 'shell', 'quick', 'merge', 'heap'].map((a) => [a, run('sorting', { algo: a, values: v })]))
  const rd = run('sorting', { algo: 'radix', values: '170 45 75 90 802 24 2 66' })
  return lesson({
    title: 'Sorting algorithms',
    kicker: 'ENCT 252 · Data Structure and Algorithms · Chapter 7',
    subtitle: 'Eight ways to put numbers in order — and why “how many comparisons” is the question.',
    sections: [
      sec('props', '7.1', 'What to ask of a sort', { eyebrow: 'Vocabulary',
        body: `<p>Sorting puts records in order by a key. Properties: ${term('internal')} (fits in memory) versus ${term('external')} (merges from disk); ${term('stable')} (equal keys keep their relative order — important when sorting by one column after another); ${term('in place')} (O(1) extra memory); ${term('adaptive')} (faster on nearly-sorted input). Compare with the same seven numbers 5 1 4 2 8 9 3 in the figures below.</p>`,
        qs: [q('stable', 'A stable sort…', ['Keeps equal keys in their original relative order.', 'Sort names by city, then by surname: a stable second pass keeps city order within equal surnames.'], [['Never changes the input.', 'It returns sorted output.'], ['Always runs in O(n log n).', 'Stability is unrelated to speed.']])] }),
      sec('simple', '7.2', 'Bubble, selection, insertion', { eyebrow: 'The O(n²) family',
        body: `<p>${term('Bubble sort')} repeatedly swaps adjacent out-of-order pairs; the largest value “bubbles” to the end each pass (<b>${S.bubble.comparisons}</b> comparisons, <b>${S.bubble.moves}</b> swaps here). ${term('Selection sort')} finds the minimum of the unsorted part and swaps it into place: always n(n−1)/2 comparisons (<b>${S.selection.comparisons}</b>) but at most n−1 swaps. ${term('Insertion sort')} grows a sorted prefix, inserting each new item by shifting larger ones right: great on nearly sorted data (best case O(n)).</p>`,
        figs: [lab('sorting', { algo: 'bubble', values: v }, 'Bubble sort.', ['comparisons', 'moves'], { caption: 'bubble', name: 'bu' }), lab('sorting', { algo: 'selection', values: v }, 'Selection sort.', ['comparisons', 'moves'], { caption: 'selection', name: 'se' }), lab('sorting', { algo: 'insertion', values: v }, 'Insertion sort.', ['comparisons', 'moves'], { caption: 'insertion', name: 'in' })],
        qs: [q('nearly', 'Which simple sort is best on an almost-sorted array?', ['Insertion sort — few shifts are needed.', 'Its best case is linear.'], [['Selection sort.', 'Always quadratic comparisons.'], ['Bubble sort without early exit.', 'Still does all passes.']])] }),
      sec('dc', '7.3', 'Quick sort and merge sort', { eyebrow: 'Divide and conquer',
        body: `<p>${term('Merge sort')} splits the array in half, sorts each half recursively and merges: always O(n log n), stable, but needs O(n) extra space (<b>${S.merge.comparisons}</b> comparisons here). ${term('Quick sort')} picks a pivot, partitions smaller-left/larger-right, and recurses: O(n log n) on average, in place, but O(n²) in the worst case (already sorted input with a bad pivot rule) (<b>${S.quick.comparisons}</b> comparisons).</p>`,
        figs: [lab('sorting', { algo: 'quick', values: v }, 'The pivot settles at its final place each round.', ['comparisons', 'sorted'], { caption: 'quick sort', name: 'qs' }), lab('sorting', { algo: 'merge', values: v }, 'Merging two sorted halves.', ['comparisons', 'sorted'], { caption: 'merge sort', name: 'ms' })],
        worked: [step('Why O(n log n)? Halving gives log₂n levels and each level does O(n) merging work.', '', { toc: 'Levels' }), step('For n = 1024 that is about 10 levels × 1024 ≈ 10 240 operations, versus 1 048 576 for n².', '1024\\log_2 1024\\approx 10^4\\ \\text{vs}\\ 10^6', { hero: true, toc: 'Comparison' })],
        qs: [q('qworst', 'When does quick sort degrade to O(n²)?', ['When partitions are badly unbalanced, e.g. always picking the smallest or largest element as pivot.', 'One side gets n−1 elements every time.'], [['On random input.', 'Random input is its average case.'], ['On tiny arrays.', 'Size alone does not cause it.']])] }),
      sec('heapshell', '7.4', 'Heap sort and Shell sort', { eyebrow: 'Other tricks',
        body: `<p>${term('Heap sort')} builds a max-heap then repeatedly swaps the root (largest) to the end and sifts down: O(n log n) worst case, in place, not stable (<b>${S.heap.comparisons}</b> comparisons here). ${term('Shell sort')} runs insertion sort on elements far apart first (gap sequence n/2, n/4, …, 1) so elements move long distances early: no simple tight bound but far better than plain insertion in practice.</p>`,
        figs: [lab('sorting', { algo: 'heap', values: v }, 'Heap sort.', ['comparisons'], { caption: 'heap sort', name: 'hs' }), lab('sorting', { algo: 'shell', values: v }, 'Shell sort.', ['comparisons'], { caption: 'shell sort', name: 'sh' })],
        qs: [q('heapz', 'Heap sort’s main advantage over merge sort?', ['It sorts in place with guaranteed O(n log n).', 'Merge sort needs O(n) extra space.'], [['It is stable.', 'Heap sort is not stable.'], ['It is faster on sorted input.', 'Not specially.']])] }),
      sec('radix', '7.5', 'Radix sort: no comparisons', { eyebrow: 'Beating n log n',
        body: `<p>Any sort that <em>compares</em> keys needs Ω(n log n) comparisons in the worst case. ${term('Radix sort')} avoids comparing: it distributes numbers into ten buckets by the least significant digit, collects them in order (stably), then repeats for the next digit. With <i>d</i> digits it costs O(d·n). 170 45 75 90 802 24 2 66 becomes <b>${rd.sorted}</b>.</p>`,
        figs: [lab('sorting', { algo: 'radix', values: '170 45 75 90 802 24 2 66' }, 'One stable pass per digit.', ['sorted'], { caption: 'LSD radix sort', name: 'rx' })],
        qs: [q('rx', 'Why must each radix pass be stable?', ['So the order from earlier (less significant) digits survives within each later bucket.', 'Otherwise earlier work would be undone.'], [['To use less memory.', 'Unrelated.'], ['Because buckets are small.', 'Unrelated.']])],
        probs: [pr('p-cmp', '<p>Sort 5 1 4 2 8 9 3 with each algorithm and compare the comparison counts.</p>', `Bubble ${S.bubble.comparisons}, selection ${S.selection.comparisons}, insertion ${S.insertion.comparisons}, shell ${S.shell.comparisons}, quick ${S.quick.comparisons}, merge ${S.merge.comparisons}, heap ${S.heap.comparisons}. The quadratic sorts do visibly more work, and the gap widens quickly with n.`)] }),
      sec('summary', '7.6', 'Summary', { eyebrow: 'Recap', body: `<table><thead><tr><th>Sort</th><th>Best</th><th>Worst</th><th>Stable</th><th>In place</th></tr></thead><tbody><tr><td>Bubble</td><td>n</td><td>n²</td><td>yes</td><td>yes</td></tr><tr><td>Insertion</td><td>n</td><td>n²</td><td>yes</td><td>yes</td></tr><tr><td>Selection</td><td>n²</td><td>n²</td><td>no</td><td>yes</td></tr><tr><td>Merge</td><td>n log n</td><td>n log n</td><td>yes</td><td>no</td></tr><tr><td>Quick</td><td>n log n</td><td>n²</td><td>no</td><td>yes</td></tr><tr><td>Heap</td><td>n log n</td><td>n log n</td><td>no</td><td>yes</td></tr></tbody></table>` }),
    ],
  })
}
