'use client'

// Truth tables, generated by actually SIMULATING the circuit.
//
// Nothing here reasons about logic symbolically. For every input combination
// we build the real circuit, force the chosen inputs to that pattern, run the
// solver until it settles, and read the chosen outputs back. Whatever the
// board does, the table says — including gates wired in ways no textbook
// covers.
//
// Each row rebuilds the circuit so component state (flip-flops, counters)
// starts clean and rows can't contaminate each other.

import type { SceneObject } from '@/lib/scene/types'
import { num } from '@/lib/scene/types'
import { buildCircuit, stepCircuit, type Circuit } from './engine'

const DT = 1 / 120
/** Steps per row. The digital pass is a fixpoint, so this only has to be
 *  enough for a value to ripple through the deepest chain of gates. */
const SETTLE = 16

/** Components a truth table can DRIVE — the things you'd flip by hand. */
const SOURCE_SYMBOLS: Record<string, string> = {
  input: 'value', // logic input → its `value` param
  switch: 'closed', // a switch is a 1-bit input too
}

/** Components a truth table can READ. */
const SINK_SYMBOLS = new Set(['output', 'logic-probe', 'led', 'bulb'])

const symbolOf = (o: SceneObject): string | undefined =>
  o.geometry.kind === 'symbol' ? o.geometry.symbol : undefined

export const isTruthSource = (o: SceneObject): boolean => {
  const s = symbolOf(o)
  return !!s && s in SOURCE_SYMBOLS
}

export const isTruthSink = (o: SceneObject): boolean => {
  const s = symbolOf(o)
  return !!s && SINK_SYMBOLS.has(s)
}

/** Everything on the page this table could use, in placement order. */
export function truthCandidates(objects: SceneObject[]): {
  sources: SceneObject[]
  sinks: SceneObject[]
} {
  return {
    sources: objects.filter(isTruthSource),
    sinks: objects.filter(isTruthSink),
  }
}

export interface TruthTable {
  inputs: { id: string; name: string }[]
  outputs: { id: string; name: string }[]
  /** 2^n rows; `ins` and `outs` are 0/1, aligned with the columns above. */
  rows: { ins: number[]; outs: number[] }[]
  /** Set when the table couldn't be produced — shown instead of the grid. */
  error?: string
}

/** Read one sink as a logic level, whatever kind of sink it is. */
function readLogic(c: Circuit, id: string): number {
  const r = c.frame.readings.get(id)
  if (!r) return 0
  const ch = r.channels ?? {}
  if (typeof ch.value === 'number') return ch.value >= 0.5 ? 1 : 0
  if (typeof ch.level === 'number') return ch.level >= 0.5 ? 1 : 0
  // LED / bulb: lit counts as 1.
  if (typeof r.glow === 'number') return r.glow >= 0.5 ? 1 : 0
  return 0
}

export const MAX_INPUTS = 8 // 256 rows — past that a table stops being readable

/**
 * Simulate every input combination and tabulate the outputs.
 * `objects` is the whole page; ids pick the columns.
 */
export function computeTruthTable(
  objects: SceneObject[],
  inputIds: string[],
  outputIds: string[]
): TruthTable {
  const byId = new Map(objects.map((o) => [o.id, o]))
  const inputs = inputIds
    .map((id) => byId.get(id))
    .filter((o): o is SceneObject => !!o && isTruthSource(o))
  const outputs = outputIds
    .map((id) => byId.get(id))
    .filter((o): o is SceneObject => !!o && isTruthSink(o))

  const cols = {
    inputs: inputs.map((o) => ({ id: o.id, name: o.name })),
    outputs: outputs.map((o) => ({ id: o.id, name: o.name })),
  }
  if (inputs.length === 0 || outputs.length === 0) {
    return { ...cols, rows: [], error: 'Pick at least one input and one output.' }
  }
  if (inputs.length > MAX_INPUTS) {
    return { ...cols, rows: [], error: `Too many inputs (max ${MAX_INPUTS}).` }
  }

  const rows: TruthTable['rows'] = []
  const total = 1 << inputs.length

  for (let pattern = 0; pattern < total; pattern++) {
    // Standard ordering: the FIRST input column is the most significant bit,
    // so the table counts up the way it's written on a page.
    const ins = inputs.map((_, i) => (pattern >> (inputs.length - 1 - i)) & 1)

    // Override just the driven inputs; everything else is the page as drawn.
    const forced = objects.map((o) => {
      const idx = inputs.findIndex((inp) => inp.id === o.id)
      if (idx < 0) return o
      const param = SOURCE_SYMBOLS[symbolOf(o) as string]
      return { ...o, parameters: { ...o.parameters, [param]: num(String(ins[idx])) } }
    })

    const circuit = buildCircuit(forced)
    if (!circuit) {
      return { ...cols, rows: [], error: 'No circuit found on this page.' }
    }
    const map = Object.fromEntries(forced.map((o) => [o.id, o]))
    for (let k = 0; k < SETTLE; k++) stepCircuit(circuit, DT, k * DT, map)

    rows.push({ ins, outs: outputs.map((o) => readLogic(circuit, o.id)) })
  }

  return { ...cols, rows }
}
