// The universal object model, v2 — entity/component architecture.
//
// An object is GEOMETRY (dumb shape) + BEHAVIORS (attached meaning).
// A circle is just a circle until a `rigidBody` behavior is attached; then
// Play simulates it. A zigzag line with a `spring` behavior IS a spring.
// Nothing on the canvas is special-cased: notes, sketches and physical
// bodies share this one shape (see docs/architecture.md).

export interface Vec2 {
  x: number
  y: number
}

export interface NumericParam {
  kind: 'number'
  expr: string // user-editable expression: "5", "m", "density*volume"
  value: number // cached evaluation against the page scope
  error?: string
}

export interface StringParam {
  kind: 'string'
  value: string
}

export interface BoolParam {
  kind: 'bool'
  value: boolean
}

export type ParamValue = NumericParam | StringParam | BoolParam

// ── Geometry ────────────────────────────────────────────────────────────────

export type GeometryKind =
  | 'circle' // bbox-inscribed ellipse/circle
  | 'rect'
  | 'polygon' // closed; points relative to position, within size bbox
  | 'line' // two-point segment (also: beams, connectors)
  | 'stroke' // freehand ink, unrecognized
  | 'text'
  | 'note'
  | 'formula'
  | 'graph'
  | 'surface3d' // 3D surface/implicit-equation plotter — z=f(x,y) or x^2+y^2+z^2=25
  | 'chart' // bar/line/area/scatter/pie chart with an inline editable data table
  | 'cashflow' // engineering-economics cash-flow timeline
  | 'truthtable' // digital truth table, generated by simulating the circuit
  | 'table'      // excel-like table component
  | 'gridtable'  // transparent MS Word / Canva grid table
  | 'slider'     // customizable placeable slider tool
  | 'button'     // customizable placeable button tool
  | 'trigger'    // conditional comparison trigger tool
  | 'symbol' // schematic symbol (resistor, gate, hinge…)
  | 'code' // code editor / IDE for SimScript
  | 'dsa' // DSA Lab — C++ IDE + line-by-line algorithm visualizer
  | 'picture' // static raster image placed on the canvas (opfs:<fileId> src) — not the whole-page 'image' PageKind

export interface Geometry {
  kind: GeometryKind
  /** polygon/stroke/line: points relative to object position */
  points?: number[][]
  /** symbol: which glyph (e.g. 'resistor', 'and-gate', 'hinge') */
  symbol?: string
  /** symbol: domain it belongs to ('mechanics' | 'electrical' | …) */
  domain?: string
  /** picture: `opfs:<fileId>` resolving via lib/storage/manager.ts, same
   *  convention PageNode.fileUrl already uses. */
  src?: string
}

// ── Behaviors (components in the Unity sense) ───────────────────────────────

export type BehaviorType =
  | 'rigidBody' // dynamic body: mass, friction, restitution, velocity
  | 'staticBody' // immovable collider (ground, walls, anchors)
  | 'spring' // on line-ish geometry: connects whatever its endpoints touch
  | 'rope' // distance constraint
  | 'rod' // rigid link
  | 'damper' // dashpot
  | 'hinge' // revolute joint at this object's center (pins overlapping bodies)
  | 'motor' // drives angular velocity of the body it's attached to
  | 'force' // fx/fy expressions applied every frame
  | 'wire' // conductor: joins the circuit terminals it touches
  | 'electricalNode' // circuit solver participation (symbols)
  | 'charge' // point charge on a rigid body: Coulomb force + qE, qv×B
  | 'efield' // region behavior (rect/circle): uniform electric field inside it
  | 'bfield' // region behavior (rect/circle): uniform B field (out of plane) inside it
  | 'dielectric' // region (rect/circle): relative permittivity — real SI E, D and energy density
  | 'torsionSpring' // on a hinge: angular restoring torque toward a rest angle
  | 'heatSource' // thermal emission — see Phase F
  | 'sensor' // roadmap: triggers/measurement region
  | 'lightSource' // on a circle: fires a ray bundle for the optics ray tracer
  | 'thinLens' // on a line: paraxial thin-lens refraction (focal length f)
  | 'opticalMirror' // on a line: specular reflection
  | 'opticalScreen' // on a line: absorbs rays, marks where they land
  | 'slit' // on a line: blocks rays except through 1–2 gaps
  | 'waveSource' // on a circle: emits an animated plane wave along its rotation
  | 'waveBoundary' // on a line: normal-incidence interface between two declared media
  | 'transmissionLine' // on a line: Z0/length/load — input impedance + SWR pattern
  | 'quantumWell' // on a rect: particle-in-a-box — wavefunction/probability/energy levels
  | 'tunnelBarrier' // on a rect: rectangular barrier — tunneling T/R
  | 'custom'

export interface Behavior {
  id: string
  type: BehaviorType
  enabled: boolean
  params: Record<string, ParamValue>
}

// ── Scene object ────────────────────────────────────────────────────────────

export interface SceneObject {
  id: string
  name: string
  geometry: Geometry
  position: Vec2 // top-left of bbox, page coords
  size: { w: number; h: number }
  rotation: number // degrees, edit-time
  z: number
  behaviors: Behavior[]
  /** Content parameters (note text, formula latex, graph bindings…) */
  parameters: Record<string, ParamValue>
  metadata: Record<string, unknown>
}

export interface Variable {
  id: string
  name: string
  expr: string
  value: number
  error?: string
}

export interface PageDoc {
  objects: Record<string, SceneObject>
  variables: Variable[]
}

/** What a notebook page IS: an infinite board, a paged document (also the
 *  Word-file/.docx role — exports to both .pdf and .docx), a presentation
 *  (same sheet-of-SceneObjects engine as doc, laid out as a slide deck +
 *  Present mode instead of a scrolling document), an uploaded PDF you read
 *  and annotate, an uploaded image you view and annotate, or an editable
 *  spreadsheet. Older pages have no kind → board. */
export type PageKind = 'board' | 'doc' | 'pdf' | 'image' | 'xlsx' | 'pptx' | 'web'

/** The notebook/folder tree — Notebook -> Section -> Page used to be a fixed
 *  2-level hierarchy; it's now arbitrary-depth folders that can contain
 *  folders, pages, or raw uploaded files, like a real filesystem. A
 *  "Notebook" is no longer a distinct type — it's just a FolderNode with
 *  `parentId: null` (top-level), rendered specially in the UI (cover image,
 *  emoji, notebook picker) because of that, not because it's a different
 *  kind of thing. IDs are globally unique (see `uid()` below), so lookup
 *  never needs a parent-scoped path — every consumer can go straight from an
 *  id to its node via a flat map. */
export type NodeKind = 'folder' | 'page' | 'file'

interface NodeBase {
  id: string
  /** null = top-level ("notebook"). */
  parentId: string | null
  name: string
  /** Sibling sort key — replaces array-position ordering now that the tree
   *  isn't stored as nested arrays. */
  order: number
}

export interface FolderNode extends NodeBase {
  kind: 'folder'
  /** Only meaningful when parentId === null (was Notebook.emoji). */
  emoji?: string
  /** Cover image path (from /public/cover), only meaningful when
   *  parentId === null (was Notebook.cover). */
  cover?: string
  /** Only meaningful when parentId !== null (was Section.color). */
  color?: string
  /**
   * Does every page and file under this folder sync across devices?
   *
   * Opt-in, default false — see lib/sync/page-sync.ts. Cascades: all descendant
   * pages and files are treated as sync-enabled when this is true, regardless of
   * their individual flags. Optional so folders written before this field existed
   * keep loading; readers treat `undefined` as false.
   */
  syncEnabled?: boolean
}

/** Tree metadata only — page content lives in the document store, keyed by id. */
export interface PageNode extends NodeBase {
  kind: 'page'
  /**
   * Does this page's CONTENT (and its images' bytes) leave the device?
   *
   * Opt-in, default false — see lib/sync/page-sync.ts. The node itself always
   * syncs so other devices know the page exists; this gates the simblip_pages
   * content rows and the blob uploads. Optional so pages written before the
   * toggle existed keep loading; readers treat `undefined` as false.
   */
  syncEnabled?: boolean
  /** What this page IS: an infinite board, a paged document, or an uploaded
   *  PDF/PPT you read and annotate. Older pages have no kind → board. */
  pageKind?: PageKind
  /** doc: ordered content-page ids, one per sheet. */
  docPages?: string[]
  /** doc: per-sheet page size overrides (CSS px, A4 ratio by default), keyed by sheet id. */
  sheetSizes?: Record<string, { w: number; h: number }>
  /** doc/pptx: per-sheet background color override (CSS color string),
   *  keyed by sheet id — a pptx slide's <p:bg> solid fill reproduces here.
   *  Unset sheets keep the default white/dark-neutral. */
  sheetColors?: Record<string, string>
  /** doc: page size chosen at creation (see lib/scene/doc-page-sizes.ts) — the
   *  default every NEW sheet gets until individually resized. A sheetSizes
   *  entry always overrides this for that sheet. */
  docPageSize?: { w: number; h: number }
  /** doc: subtitle shown under the title in the compulsory first-page header. */
  docSubtitle?: string
  /** doc: date shown in the compulsory first-page header, ISO (YYYY-MM-DD).
   *  Unset shows today's date without persisting it, so it stays current
   *  until someone deliberately picks a different one. */
  docDate?: string
  /** pdf: content-page ids for linked per-PDF-page notes (index = pdf page − 1). */
  notesPages?: string[]
  /** pdf: content-page ids for direct on-page ink, one real canvas per PDF
   *  page (index = pdf page − 1) — the same pen/eraser/undo as a board. */
  annotPages?: string[]
  /** pdf: id of the free-form notes doc opened beside the reader. */
  notesDocId?: string
  /** pdf: where the reader was left — the 1-based page number plus the
   *  fraction of that page already scrolled past, so reopening lands on the
   *  exact spot rather than back at page 1. Stored as an offset WITHIN a
   *  page (not a raw scrollTop) so it survives a zoom change or a different
   *  window size, where pixel offsets would not. */
  pdfScroll?: { page: number; offset: number }
  /** pdf/image/xlsx/pptx: the source file, `opfs:<fileId>` resolving via
   *  lib/storage/manager.ts. For pdf this is a legacy attachment path for
   *  pages created before file nodes existed — prefer a FileNode leaf for
   *  new uploads. For image/xlsx/pptx this is how the page's companion
   *  FileNode (see FileNode.pageId) hands off its bytes for import on
   *  first open. */
  fileUrl?: string
  fileName?: string
  fileMime?: string
  /** image: id of the single ink overlay page (like one annotPages slot,
   *  but an image is always one page — no array needed). */
  imageAnnotPageId?: string
  /** xlsx: spreadsheet grid JSON (x-data-spreadsheet's own sheet format). */
  xlsxContent?: unknown
  /** web: current URL being browsed or cached. */
  webUrl?: string
  /** web: title of the active web page. */
  webTitle?: string
  /** web: navigation history stack. */
  webHistory?: string[]
  /** web: index in navigation history stack. */
  webHistoryIndex?: number
  /** web: saved bookmarks. */
  webBookmarks?: { url: string; title: string }[]
  /** web: offline cached HTML content snapshot. */
  webCachedHtml?: string
  /** web: offline cached readable text content. */
  webCachedText?: string
  /** web: id of the ink annotation overlay canvas. */
  webAnnotPageId?: string
}

/** A raw uploaded file as a direct tree leaf (PDF, image, etc.) — not
 *  wrapped in a page. `fileId` resolves the actual blob via the OPFS +
 *  manifest storage layer (lib/storage/manager.ts). */
export interface FileNode extends NodeBase {
  kind: 'file'
  fileId: string
  mime: string
  size: number
  /** Lazily created on first open (see components/workspace/open-file.ts) —
   *  the viewer/editor PageNode this file's content is imported into.
   *  Subsequent opens reuse it instead of re-importing. Absent until first
   *  opened, or for mime types with no viewer (stays a plain tree leaf). */
  pageId?: string
}

export type Node = FolderNode | PageNode | FileNode

/** @deprecated kept only for the one-time legacy-shape migration
 *  (lib/store/migrate-tree.ts) — do not use in new code. */
export interface PageMeta {
  id: string
  name: string
  kind?: PageKind
  docPages?: string[]
  sheetSizes?: Record<string, { w: number; h: number }>
  docPageSize?: { w: number; h: number }
  docSubtitle?: string
  docDate?: string
  notesPages?: string[]
  annotPages?: string[]
  notesDocId?: string
  fileUrl?: string
  fileName?: string
  fileMime?: string
}

/** @deprecated kept only for the one-time legacy-shape migration
 *  (lib/store/migrate-tree.ts) — do not use in new code. */
export interface Section {
  id: string
  name: string
  color: string
  pages: PageMeta[]
}

/** @deprecated kept only for the one-time legacy-shape migration
 *  (lib/store/migrate-tree.ts) — do not use in new code. */
export interface Notebook {
  id: string
  name: string
  emoji: string
  cover?: string
  sections: Section[]
}

export const num = (expr: string | number, value?: number): NumericParam => {
  const e = String(expr)
  return { kind: 'number', expr: e, value: value ?? (Number.isFinite(Number(e)) ? Number(e) : 0) }
}

export const str = (value: string): StringParam => ({ kind: 'string', value })
export const bool = (value: boolean): BoolParam => ({ kind: 'bool', value })

export const uid = () =>
  `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`
