// The universal object model, v2 — entity/component architecture.
//
// An object is GEOMETRY (dumb shape) + BEHAVIORS (attached meaning).
// A circle is just a circle until a `rigidBody` behavior is attached; then
// Play simulates it. A zigzag line with a `spring` behavior IS a spring.
// Nothing on the canvas is special-cased: notes, sketches and physical
// bodies share this one shape (see docs/architecture.md).

export interface Vec2 {
  x: number
  y: number
}

export interface NumericParam {
  kind: 'number'
  expr: string // user-editable expression: "5", "m", "density*volume"
  value: number // cached evaluation against the page scope
  error?: string
}

export interface StringParam {
  kind: 'string'
  value: string
}

export interface BoolParam {
  kind: 'bool'
  value: boolean
}

export type ParamValue = NumericParam | StringParam | BoolParam

// ── Geometry ────────────────────────────────────────────────────────────────

export type GeometryKind =
  | 'circle' // bbox-inscribed ellipse/circle
  | 'rect'
  | 'polygon' // closed; points relative to position, within size bbox
  | 'line' // two-point segment (also: beams, connectors)
  | 'stroke' // freehand ink, unrecognized
  | 'text'
  | 'note'
  | 'formula'
  | 'graph'
  | 'surface3d' // 3D surface/implicit-equation plotter — z=f(x,y) or x^2+y^2+z^2=25
  | 'chart' // bar/line/area/scatter/pie chart with an inline editable data table
  | 'cashflow' // engineering-economics cash-flow timeline
  | 'truthtable' // digital truth table, generated by simulating the circuit
  | 'table'      // excel-like table component
  | 'gridtable'  // transparent MS Word / Canva grid table
  | 'slider'     // customizable placeable slider tool
  | 'button'     // customizable placeable button tool
  | 'trigger'    // conditional comparison trigger tool
  | 'symbol' // schematic symbol (resistor, gate, hinge…)
  | 'code' // code editor / IDE for SimScript
  | 'dsa' // DSA Lab — C++ IDE + line-by-line algorithm visualizer

export interface Geometry {
  kind: GeometryKind
  /** polygon/stroke/line: points relative to object position */
  points?: number[][]
  /** symbol: which glyph (e.g. 'resistor', 'and-gate', 'hinge') */
  symbol?: string
  /** symbol: domain it belongs to ('mechanics' | 'electrical' | …) */
  domain?: string
}

// ── Behaviors (components in the Unity sense) ───────────────────────────────

export type BehaviorType =
  | 'rigidBody' // dynamic body: mass, friction, restitution, velocity
  | 'staticBody' // immovable collider (ground, walls, anchors)
  | 'spring' // on line-ish geometry: connects whatever its endpoints touch
  | 'rope' // distance constraint
  | 'rod' // rigid link
  | 'damper' // dashpot
  | 'hinge' // revolute joint at this object's center (pins overlapping bodies)
  | 'motor' // drives angular velocity of the body it's attached to
  | 'force' // fx/fy expressions applied every frame
  | 'wire' // conductor: joins the circuit terminals it touches
  | 'electricalNode' // circuit solver participation (symbols)
  | 'charge' // point charge on a rigid body: Coulomb force + qE, qv×B
  | 'efield' // region behavior (rect/circle): uniform electric field inside it
  | 'bfield' // region behavior (rect/circle): uniform B field (out of plane) inside it
  | 'torsionSpring' // on a hinge: angular restoring torque toward a rest angle
  | 'heatSource' // thermal emission — see Phase F
  | 'sensor' // roadmap: triggers/measurement region
  | 'lightSource' // on a circle: fires a ray bundle for the optics ray tracer
  | 'thinLens' // on a line: paraxial thin-lens refraction (focal length f)
  | 'opticalMirror' // on a line: specular reflection
  | 'opticalScreen' // on a line: absorbs rays, marks where they land
  | 'slit' // on a line: blocks rays except through 1–2 gaps
  | 'waveSource' // on a circle: emits an animated plane wave along its rotation
  | 'waveBoundary' // on a line: normal-incidence interface between two declared media
  | 'transmissionLine' // on a line: Z0/length/load — input impedance + SWR pattern
  | 'quantumWell' // on a rect: particle-in-a-box — wavefunction/probability/energy levels
  | 'tunnelBarrier' // on a rect: rectangular barrier — tunneling T/R
  | 'custom'

export interface Behavior {
  id: string
  type: BehaviorType
  enabled: boolean
  params: Record<string, ParamValue>
}

// ── Scene object ────────────────────────────────────────────────────────────

export interface SceneObject {
  id: string
  name: string
  geometry: Geometry
  position: Vec2 // top-left of bbox, page coords
  size: { w: number; h: number }
  rotation: number // degrees, edit-time
  z: number
  behaviors: Behavior[]
  /** Content parameters (note text, formula latex, graph bindings…) */
  parameters: Record<string, ParamValue>
  metadata: Record<string, unknown>
}

export interface Variable {
  id: string
  name: string
  expr: string
  value: number
  error?: string
}

export interface PageDoc {
  objects: Record<string, SceneObject>
  variables: Variable[]
}

/** What a notebook page IS: an infinite board, a paged document, or an
 *  uploaded PDF/PPT you read and annotate. Older pages have no kind → board. */
export type PageKind = 'board' | 'doc' | 'pdf'

/** The notebook/folder tree — Notebook -> Section -> Page used to be a fixed
 *  2-level hierarchy; it's now arbitrary-depth folders that can contain
 *  folders, pages, or raw uploaded files, like a real filesystem. A
 *  "Notebook" is no longer a distinct type — it's just a FolderNode with
 *  `parentId: null` (top-level), rendered specially in the UI (cover image,
 *  emoji, notebook picker) because of that, not because it's a different
 *  kind of thing. IDs are globally unique (see `uid()` below), so lookup
 *  never needs a parent-scoped path — every consumer can go straight from an
 *  id to its node via a flat map. */
export type NodeKind = 'folder' | 'page' | 'file'

interface NodeBase {
  id: string
  /** null = top-level ("notebook"). */
  parentId: string | null
  name: string
  /** Sibling sort key — replaces array-position ordering now that the tree
   *  isn't stored as nested arrays. */
  order: number
}

export interface FolderNode extends NodeBase {
  kind: 'folder'
  /** Only meaningful when parentId === null (was Notebook.emoji). */
  emoji?: string
  /** Cover image path (from /public/cover), only meaningful when
   *  parentId === null (was Notebook.cover). */
  cover?: string
  /** Only meaningful when parentId !== null (was Section.color). */
  color?: string
}

/** Tree metadata only — page content lives in the document store, keyed by id. */
export interface PageNode extends NodeBase {
  kind: 'page'
  /** What this page IS: an infinite board, a paged document, or an uploaded
   *  PDF/PPT you read and annotate. Older pages have no kind → board. */
  pageKind?: PageKind
  /** doc: ordered content-page ids, one per sheet. */
  docPages?: string[]
  /** doc: per-sheet page size overrides (CSS px, A4 ratio by default), keyed by sheet id. */
  sheetSizes?: Record<string, { w: number; h: number }>
  /** doc: page size chosen at creation (see lib/scene/doc-page-sizes.ts) — the
   *  default every NEW sheet gets until individually resized. A sheetSizes
   *  entry always overrides this for that sheet. */
  docPageSize?: { w: number; h: number }
  /** doc: subtitle shown under the title in the compulsory first-page header. */
  docSubtitle?: string
  /** doc: date shown in the compulsory first-page header, ISO (YYYY-MM-DD).
   *  Unset shows today's date without persisting it, so it stays current
   *  until someone deliberately picks a different one. */
  docDate?: string
  /** pdf: content-page ids for linked per-PDF-page notes (index = pdf page − 1). */
  notesPages?: string[]
  /** pdf: content-page ids for direct on-page ink, one real canvas per PDF
   *  page (index = pdf page − 1) — the same pen/eraser/undo as a board. */
  annotPages?: string[]
  /** pdf: id of the free-form notes doc opened beside the reader. */
  notesDocId?: string
  /** pdf: shareable copy of the uploaded document — legacy attachment path
   *  for pdf-kind pages created before file nodes existed (cloud/local db,
   *  or `opfs:<manifestId>` once migrated). Prefer a FileNode leaf for new
   *  uploads instead of wrapping them in a pdf-kind page. */
  fileUrl?: string
  fileName?: string
  fileMime?: string
}

/** A raw uploaded file as a direct tree leaf (PDF, image, etc.) — not
 *  wrapped in a page. `fileId` resolves the actual blob via the OPFS +
 *  manifest storage layer (lib/storage/manager.ts). */
export interface FileNode extends NodeBase {
  kind: 'file'
  fileId: string
  mime: string
  size: number
}

export type Node = FolderNode | PageNode | FileNode

/** @deprecated kept only for the one-time legacy-shape migration
 *  (lib/store/migrate-tree.ts) — do not use in new code. */
export interface PageMeta {
  id: string
  name: string
  kind?: PageKind
  docPages?: string[]
  sheetSizes?: Record<string, { w: number; h: number }>
  docPageSize?: { w: number; h: number }
  docSubtitle?: string
  docDate?: string
  notesPages?: string[]
  annotPages?: string[]
  notesDocId?: string
  fileUrl?: string
  fileName?: string
  fileMime?: string
}

/** @deprecated kept only for the one-time legacy-shape migration
 *  (lib/store/migrate-tree.ts) — do not use in new code. */
export interface Section {
  id: string
  name: string
  color: string
  pages: PageMeta[]
}

/** @deprecated kept only for the one-time legacy-shape migration
 *  (lib/store/migrate-tree.ts) — do not use in new code. */
export interface Notebook {
  id: string
  name: string
  emoji: string
  cover?: string
  sections: Section[]
}

export const num = (expr: string | number, value?: number): NumericParam => {
  const e = String(expr)
  return { kind: 'number', expr: e, value: value ?? (Number.isFinite(Number(e)) ? Number(e) : 0) }
}

export const str = (value: string): StringParam => ({ kind: 'string', value })
export const bool = (value: boolean): BoolParam => ({ kind: 'bool', value })

export const uid = () =>
  `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`
